<!DOCTYPE doctype PUBLIC "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
            
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
            
  <meta name="GENERATOR"
 content="Mozilla/4.73 [en] (WinNT; I) [Netscape]">
  <title>Main Page</title>
                   
  <link href="doxygen.css" rel="stylesheet" type="text/css">
</head>
  <body>
   &nbsp;   
<center>  
<table width="96%">
   <tbody>
      <tr>
   <td><a href="http://www.opencascade.com"><img src="sources/ogocorp.gif"
 border="0" height="46" width="122">
        </a></td>
     <td>               
      <div align="right"><a href="http://www.opencascade.org/SALOME/"><img
 src="sources/application.gif" border="0" height="46" width="108">
        </a></div>
   </td>
   </tr>
         
  </tbody>  
</table>
  </center>
       
<h1><a name="page2">Examples</a> </h1>
     <br>
  <br>
   
<div align="justify">&nbsp;&nbsp;&nbsp; &nbsp;<big><b><i> <small>Interfaces:</small></i></b></big><br>
  <br>
  &nbsp; &nbsp; &nbsp; <a href="#SALOMEDS::Study_impl">SALOMEDS::Study</a><br>
  &nbsp;&nbsp;&nbsp; &nbsp; <a href="#SALOMEDS::StudyBuilder_impl">SALOMEDS::StudyBuilder</a><br>
  &nbsp;&nbsp; &nbsp;&nbsp; <a href="#SALOMEDS::StudyManager_impl">SALOMEDS::StudyManager</a><br>
  &nbsp;&nbsp;&nbsp; &nbsp; <a href="#SALOMEDS::SObject_impl">SALOMEDS::SObject</a><br>
&nbsp;&nbsp;&nbsp; &nbsp; <a href="#SALOMEDS::SComponent_impl">SALOMEDS::SComponent</a><br>
  &nbsp; &nbsp; &nbsp; <a href="#SALOMEDS::SComponentIterator_impl">SALOMEDS::SComponentIterator</a><br>
  &nbsp; &nbsp; &nbsp; <a href="#SALOMEDS::ChildIterator_impl">SALOMEDS::ChildIterator<br>
 </a> &nbsp; &nbsp; &nbsp;<a href="#SALOMEDS::AttributeComment_impl"> SALOMEDS::AttributeComment</a><br>
   &nbsp;&nbsp;&nbsp; &nbsp;<br>
  </div>
  <br>
  <br>
  <br>
   
<div align="center">&nbsp;&nbsp;&nbsp; &nbsp; <small><small><u><big><big><a
 name="SALOMEDS::Study_impl"></a><font color="#000000"
 face="Helvetica, Arial, sans-serif"><big><big><b>SALOMEDS::Study interface</b></big></big></font></big></big></u></small></small><br>
  <br>
   
<div align="left">                  <big><br>
  </big></div>
  <big><br>
  </big>  
<div align="left"><b><big><a class="el"
 href="interfaceSALOMEDS_1_1SComponent.html">SComponent</a>  FindComponent(
in string <i>aComponentName </i>)</big></b><br>
  <i><br>
  <u>Find GEOMETRY component in the opened study by its name:</u></i><br>
  <br>
  &nbsp;&nbsp;&nbsp; str= os.getenv("TmpDir")<br>
  &nbsp;&nbsp;&nbsp; if str == None:<br>
  &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; str = "/tmp"<br>
  &nbsp;&nbsp;&nbsp; file = str+"/test.hdf"<br>
  <br>
  &nbsp;&nbsp;&nbsp; openedStudy=batchmode_geompy.myStudyManager.Open(file)<br>
  <br>
  &nbsp;&nbsp;&nbsp; father = openedStudy.FindComponent("GEOM")<br>
  &nbsp;&nbsp;&nbsp; if father is None:<br>
  &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;raise&nbsp; RuntimeError, "Geom
 component is not found!&nbsp; Wrong study is opened." <br>
  <br>
  <br>
  </div>
   
<div align="left"><b><big><a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a>  FindObject ( in string
<em>anObjectName </em>)</big></b><br>
  <br>
  <u><i>Find the SObject of the box by its NameAttribute "box":</i></u><br>
  </div>
   
<div align="left"><br>
  </div>
   
<div align="left">box = openedStudy.FindObject("box")<br>
  if box is None :<br>
  &nbsp;&nbsp;&nbsp; raise&nbsp; RuntimeError, "box was not found! Wrong
study  is opened."<br>
  <br>
  <br>
  <small><big><big><a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a></big></big><b><big><big>&nbsp;FindObjectID
 ( in</big> <big><a class="el" href="namespaceSALOMEDS.html#a1">ID</a>  </big><em><big>aObjectID
)</big><br>
  #result: "/User data/Case1". <br>
  </em><big><em></em></big><big><em></em></big></big></b></small><u><i>Find
 the SObject of the box by its ID </i>"</u><u>0:1:1:2"<i>:</i></u><br>
   <br>
  </div>
   
<div align="left">box =openedStudy.FindObjectID("0:1:1:2")<br>
  </div>
   
<div align="left">if box is None :<br>
   &nbsp;&nbsp;&nbsp; raise&nbsp; RuntimeError, "box was not found! Wrong 
ID is used."<br>
  <br>
  <br>
  <small><big><big><a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a></big></big></small><big><b>&nbsp;FindObjectIOR
 ( in&nbsp;<a class="el" href="namespaceSALOMEDS.html#a1">ID</a>&nbsp;  <em>aObjectIOR</em>
)</b></big><br>
  <br>
  <u><i>Find the SObject </i></u><u><i>of the result on imported MED file 
by it's IOR:</i></u><br>
  <br>
  theResult = myVisu.ImportFile(medFile)<br>
  aSObj = myStudy.FindObjectIOR(theResult.GetID())<br>
  <br>
  <br>
  <big><b><a class="el" href="interfaceSALOMEDS_1_1SObject.html">SObject</a>
 FindObjectByPath ( in string <i>thePath</i> )</b></big><br>
  <br>
  <u><i>Find SObject by path to it:</i></u><br>
  <i><br>
  # create new auxiliary componen</i>t<br>
  aComponent = myStudyBuilder.NewComponent("Virtual Component")<br>
  <br>
  # create auxiliary subtree<br>
  aPath = "/Virtual Component/Case1"<br>
  myStudyBuilder.AddDirectory(aPath)<br>
  <br>
  aSObj = myStudy.FindObjectByPath(aPath)<br>
  <br>
  <br>
  <big><b>void SetContext ( in string <i>thePath</i>)</b> </big><b><big><big>/</big>
 string GetContext ()</big></b><br>
  <br>
  <u><i>Set context of the study to the created case and get it for printing:</i></u><br>
  <br>
  aComponent = myStudyBuilder.NewComponent("User data")<br>
  anAttr = aBuilder.FindOrCreateAttribute(aComponent, "AttributeName")<br>
  anAttrName = anAttr._narrow(SALOMEDS.AttributeName) <br>
  anAttrName.SetValue("User data")<br>
  <br>
  #Add a new case 'Case1' to the component 'User data'<br>
  aBuilder.AddDirectory("/User data/Case1")<br>
  <br>
  #Set a study context to '/User data/Case1'<br>
  aStudy.SetContext("/User data/Case1")<br>
  <br>
  #Print the current study context<br>
  print aStudy.GetContext()<br>
  <u><small><br>
  </small><i>#result: "/User data/Case1".</i></u><br>
  <br>
  <br>
  <big><b><a class="el" href="interfaceSALOMEDS_1_1ChildIterator.html">ChildIterator</a>
 NewChildIterator ( in&nbsp;<a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a>  aSO            ) </b></big><br>
  <br>
  <u><i>Import med file and print all mesh names that this file includes
(mesh  is a child of the result of imported file):</i></u><br>
  <br>
  <i># define file name</i><br>
  aFileName = datadir + "fra.med"<br>
  <br>
  <i># import file in visu module and get result</i><br>
  theVisu = batchmode_visu.myVisu<br>
  aResult = theVisu.ImportFile(aFileName)<br>
  if aResult is None : raise RuntimeError, "Error"<br>
  else : print "OK"<br>
  &nbsp;<br>
  <i># get current study and its' SObject&nbsp; </i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 <br>
  myLocalStudy = theVisu.GetCurrentStudy()<br>
  aSObj = myLocalStudy.FindObjectIOR(aResult.GetID())<br>
  if aSObj is None : raise RuntimeError, "Error"<br>
  else : print "OK"<br>
  <br>
  <i># create iterator by SObject of the current study</i><br>
  aMeshIter = myLocalStudy.NewChildIterator(aSObj);<br>
  <br>
  <i># iterating in the current study (with the help of created iterator) 
to find all mesh names</i> &nbsp;<br>
  while aMeshIter.More() :<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; aMeshSObj = aMeshIter.Value()<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; aMeshIter.Next()<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; anAttr = aMeshSObj.FindAttribute("AttributeName")[1]<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if anAttr is None :<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; aMeshSObj
 = aMeshIter.Value()<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; aMeshIter.Next()<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; anAttr
 = aMeshSObj.FindAttribute("AttributeName")[1]<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; anAttr = anAttr._narrow(SALOMEDS.AttributeName);<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; aMeshName = anAttr.Value()<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print "&nbsp; ", aMeshName<br>
  <br>
  <br>
  <big><b><a class="el"
 href="interfaceSALOMEDS_1_1SComponentIterator.html">SComponentIterator</a> 
NewComponentIterator ()</b></big><br>
 <br>
 <u><i>Find the number an names of all components in the study:</i></u><br>
 <br>
 aCompItr = myStudy.NewComponentIterator()<br>
 <br>
 compNb = 0<br>
 while aCompItr.More():<br>
 &nbsp;&nbsp;&nbsp; aComp = aCompItr.Value()<br>
 &nbsp;&nbsp;&nbsp; aName = aComp.ComponentDataType()<br>
 &nbsp;&nbsp;&nbsp; print "Component name = ", aName<br>
 &nbsp;&nbsp;&nbsp; compNb += 1<br>
 &nbsp;&nbsp;&nbsp; aCompItr.Next()<br>
 <br>
 <br>
 <big><b><a class="el" href="interfaceSALOMEDS_1_1StudyBuilder.html">StudyBuilder</a> 
NewBuilder ()</b></big><br>
  </div>
  </div>
 <br>
 <i><u>Create a new StudyBuilder (uses to add or modify an object in the
study ):</u></i><br>
 <br>
 myBuilder = myStudy.NewBuilder() <br>
 <br>
 <br>
 <big><b><a class="el"
 href="interfaceSALOMEDS_1_1AttributeStudyProperties.html">AttributeStudyProperties</a> 
GetProperties ()</b></big><br>
 <br>
 <i><u>Get the attribute, which contains the properties of the study, and 
change properties of the study </u></i><u>by changing it</u>: <br>
 <br>
 aProperties = myStudy.GetProperties()<br>
 if aProperties == None :<br>
 &nbsp;&nbsp;&nbsp; raise&nbsp; RuntimeError, "Can't create AttributeStudyProperties 
attribute"<br>
 aProperties&nbsp;= aProperties._narrow(SALOMEDS.AttributeStudyProperties)<br>
 <br>
 A = aProperties<br>
 <br>
 <i># print stydy properties</i><br>
 print "A.GetUserName()= ", A.GetUserName()<br>
 res,mm,hh,dd,mnth,yy=A.GetCreationDate()<br>
 print "A.GetCreationDate() = ", mm,hh,dd,mnth,yy<br>
 print "A.GetCreationMode() = ", A.GetCreationMode()<br>
 print "A.IsModified() = ", A.IsModified()<br>
 print "A.IsLocked() = ", A.IsLocked()<br>
 <br>
 <i># change the properties of the study</i><br>
 if A.IsLocked() == 0 :<br>
 &nbsp;&nbsp;&nbsp; A.SetUserName("tester"); print 'A.SetUserName("tester"), 
A.GetUserName() = ', A.GetUserName()<br>
 &nbsp;&nbsp;&nbsp; A.SetCreationDate(11,11,11,11,2002); print 'A.SetCreationDate(11,11,11,11,2002), 
A.GetCreationDate() =', A.GetCreationDate()<br>
 &nbsp;&nbsp;&nbsp; print "A.IsModified() = ", A.IsModified()<br>
 A.SetLocked(1)<br>
 <br>
 <br>
 <big><b>boolean IsModified ()</b></big><br>
 <br>
 <u><i>Find if study is modified:</i></u><br>
 <br>
 IsModified = myStudy.IsModified()<br>
 <br>
 if IsModified == 1:<br>
 &nbsp;&nbsp;&nbsp; print "The study is modified and not saved"<br>
 <br>
 <br>
 <big><b>boolean IsEmpty ()</b></big><br>
 <br>
 <u><i>Find if study is empty:</i></u><br>
  <br>
  IsEmpty = myStudy.IsEmpty()<br>
  <br>
  if IsEmpty == 1:<br>
  &nbsp;&nbsp;&nbsp; print "The study is empty"<br>
 <br>
 <br>
 <br>
 <br>
 
<div align="center"><small><small><u><big><big><a
 name="SALOMEDS::StudyBuilder_impl"></a><font color="#000000"
 face="Helvetica, Arial, sans-serif"><big><big><b>SALOMEDS::StudyBuilder
interface</b></big></big></font></big></big></u></small></small><br>
 </div>
 <br>
 <br>
 <br>
 <big><b><a class="el" href="interfaceSALOMEDS_1_1SComponent.html">SComponent</a> 
NewComponent ( in string <i>ComponentDataType</i> )</b></big><br>
 <br>
 <u><i>Create Geometry SComponent:</i></u><br>
 <br>
 myBuilder = myStudy.NewBuilder()<br>
 father = myBuilder.NewComponent("GEOM")<br>
 <br>
 <big><b><br>
 void DefineComponentInstance ( in <a class="el"
 href="interfaceSALOMEDS_1_1SComponent.html">SComponent</a> <i>aComponent</i>,
in Object <i>ComponentIOR</i> )</b></big><br>
 <br>
 <u><i>Define the instance to the created geometry component:</i></u><br>
 <br>
 <i># find geom component</i><br>
 myLCC = batchmode_salome.lcc<br>
 geom = myLCC.FindOrLoadComponent("FactoryServer", "Geometry")<br>
 geom = geom._narrow(GEOM.GEOM_Gen)<br>
 geom.GetCurrentStudy(myStudyId)<br>
 <br>
 myBuilder = myStudy.NewBuilder()<br>
 <br>
 father = myBuilder.NewComponent("GEOM")<br>
 myBuilder.DefineComponentInstance(father,geom)<br>
 <br>
 <br>
 <big><b><a class="el" href="interfaceSALOMEDS_1_1SObject.html">SObject</a> 
NewObject ( in&nbsp;<a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a> <i>theFatherObject</i>
)</b></big><br>
 <br>
 <u><i>Create box and add it to study:</i></u><br>
 <br>
 from batchmode_geompy import *<br>
 <br>
 <i># create a box</i><br>
 box = geom.MakeBox(0,0,0,100,100,150)<br>
 <br>
 ior = orb.object_to_string(box)<br>
 box._set_Name(ior)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
 <br>
 <i># create Geometry SComponent</i><br>
 father = myBuilder.NewComponent("GEOM")<br>
 A1 = myBuilder.FindOrCreateAttribute(father, "AttributeName");<br>
 FName = A1._narrow(SALOMEDS.AttributeName)<br>
 FName.SetValue("Geometry")<br>
 myBuilder.DefineComponentInstance(father,geom)<br>
 <br>
 <i># add box to Study</i><br>
 myBuilder.NewCommand()<br>
 newObj = myBuilder.NewObject(father)<br>
 A1 = myBuilder.FindOrCreateAttribute(newObj, "AttributeIOR");<br>
 ObjIOR = A1._narrow(SALOMEDS.AttributeIOR)<br>
 ObjIOR.SetValue(ior)<br>
 A2 = myBuilder.FindOrCreateAttribute(newObj, "AttributeName");<br>
 ObjName = A2._narrow(SALOMEDS.AttributeName)<br>
 ObjName.SetValue("Common_operation")<br>
 id = newObj.GetID()<br>
 box._set_StudyShapeId(id)<br>
 myBuilder.CommitCommand()<br>
 <br>
 <br>
 <b><big>void RemoveObject ( in&nbsp;<a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a> <i>anObject</i> )</big></b><br>
 <br>
 <u><i># Remove CutPlanes SObject from the StudyBuilder (delete cutplanes):</i></u><br>
 <br>
 SObj=myStudy.FindObjectIOR(cutplanes.GetID())<br>
 myBuilder = newStudy.NewBuilder()<br>
 myBuilder.RemoveObject(SObj)<br>
 <br>
 <b><big><br>
 void LoadWith ( in&nbsp;<a class="el"
 href="interfaceSALOMEDS_1_1SComponent.html">SComponent</a><i> sco</i>, in
<a class="el" href="interfaceSALOMEDS_1_1Driver.html">Driver</a> <i>Engine</i>
) raises (<a class="el" href="exceptionSALOME_1_1SALOME__Exception.html">SALOME::SALOME_Exception</a>)</big></b><br>
 <br>
 <i><u># Load Visu component:</u></i><br>
 <br>
 myBuilder = openedStudy.NewBuilder()<br>
 SCom=openedStudy.FindComponent("VISU")<br>
 myBuilder.LoadWith(SCom ,myVisu)<br>
 <br>
 <br>
 <big><b><a class="el" href="interfaceSALOMEDS_1_1GenericAttribute.html">GenericAttribute</a> 
FindOrCreateAttribute ( in&nbsp;<a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a> <i>anObject</i>,&nbsp;
in string <i>aTypeOfAttribute</i>)</b></big><br>
 <br>
 <u><i>Create AttributeName attribute for created component an set value
to it:</i></u><br>
 <br>
 myBuilder = myStudy.NewBuilder()<br>
 aComponent = myBuilder.NewComponent("User data")<br>
 <br>
 anAttr = myBuilder.FindOrCreateAttribute(aComponent, "AttributeName")<br>
 <br>
 anAttrName = anAttr._narrow(SALOMEDS.AttributeName) <br>
 anAttrName.SetValue("User data")<br>
 <br>
 <br>
 <big><b>boolean FindAttribute ( in  <a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a> <i>anObject,</i> out<i>&nbsp;</i><a
 class="el" href="interfaceSALOMEDS_1_1GenericAttribute.html">GenericAttribute</a><i> 
anAttribute</i>, in string <i>aTypeOfAttribute</i> )</b></big><br>
 <big><b><br>
 </b></big><i><u>Find AttributeName attribute of the field and print the
field name:</u></i><br>
 <br>
 aFieldSObj&nbsp; = myStudy.FindObject("Head, -")<br>
 <br>
 myStudyBuilder.FindAttribute( aFieldSObj, anAttr, "AttributeName")<br>
 if res == 0:<br>
  &nbsp;&nbsp;&nbsp; raise&nbsp; RuntimeError, "Error:&nbsp; Attribute not 
found"<br>
 <br>
 anAttr = anAttr._narrow(SALOMEDS.AttributeName);<br>
 aFieldName = anAttr.Value()<br>
 print "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ", aFieldName<br>
 <br>
 <br>
 <b><big>void RemoveAttribute ( in  <a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a> <i>anObject</i>, in
string <i>aTypeOfAttribute</i> )</big></b><br>
 <big><b><br>
 </b><u><i><small>Remove AttributeSelectable attribute of the field SObject:</small></i></u><br>
 <b><br>
 </b></big>aFieldSObj&nbsp; = myStudy.FindObject("Head, -")<br>
  <br>
  myStudyBuilder.RemoveAttribute( aFieldSObj, "AttributeSelectable")<br>
 <big><b><br>
 <br>
 </b><b>void Addreference ( in&nbsp;<big>  <small><a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a></small></big><small> 
</small><i>anObject</i>, in&nbsp;</b><b>  <a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a> <i>theReferencedObject</i>
)</b></big><br>
 <br>
 <u><i>Create a reference between created SObject and the existing field:</i></u><br>
 <br>
 aFieldSObj&nbsp; = myStudy.FindObject("Head, -")<br>
 aNewSObj = myBuilder.NewObject(myVisu)<br>
 <br>
 myBuilder.Addreference(aFieldSObj, aNewSObj)<br>
 <big><b><br>
 <br>
 </b></big><big><small><i><u><a name="NewCommand_ex"></a></u></i></small></big><big><small><b><big>void 
NewCommand ()<br>
 <br>
 </big></b><i><u>Create new command wich containes actions for changing the 
properties of the study:</u></i><b><big><br>
 <br>
 </big></b></small></big>A&nbsp;= myStudy.GetProperties()<br>
 A&nbsp;= aProperties._narrow(SALOMEDS.AttributeStudyProperties)<br>
  <br>
 myBuilder = myStudy.NewBuilder()<br>
  <br>
 myBuilder.NewCommand() <i> # creates a new command</i><br>
  <br>
  <i># change the properties of the study</i><br>
  if A.IsLocked() == 0 :<br>
  &nbsp;&nbsp;&nbsp; A.SetUserName("tester"); print 'A.SetUserName("tester"), 
A.GetUserName() = ', A.GetUserName()<br>
  &nbsp;&nbsp;&nbsp; A.SetCreationDate(11,11,11,11,2002); print 'A.SetCreationDate(11,11,11,11,2002), 
A.GetCreationDate() =', A.GetCreationDate()<br>
  &nbsp;&nbsp;&nbsp; print "A.IsModified() = ", A.IsModified()<br>
  A.SetLocked(1)<br>
 <big><small><br>
 </small></big>myBuilder.CommitCommand() <i># commits all actions declared 
within the created command</i><big><br>
 <b><br>
 <br>
 void CommitCommand()<br>
 </b><small><br>
 </small><i><small>See the end of the <a href="#NewCommand_ex">previous example</a></small></i><b><br>
 <br>
 <br>
 void AbortCommand ()</b></big><br>
 <br>
 <big><small><i><u>Create new command wich containes actions for changing 
the properties of the study, cancel all declared actions:</u></i></small></big><br>
 <br>
 A&nbsp;= myStudy.GetProperties()<br>
  A&nbsp;= aProperties._narrow(SALOMEDS.AttributeStudyProperties)<br>
   <br>
  myBuilder = myStudy.NewBuilder()<br>
   <br>
  myBuilder.NewCommand() <i> # creates a new command</i><br>
   <br>
   <i># change the properties of the study</i><br>
   if A.IsLocked() == 0 :<br>
   &nbsp;&nbsp;&nbsp; A.SetUserName("tester"); print 'A.SetUserName("tester"), 
A.GetUserName() = ', A.GetUserName()<br>
   &nbsp;&nbsp;&nbsp; A.SetCreationDate(11,11,11,11,2002); print 'A.SetCreationDate(11,11,11,11,2002), 
A.GetCreationDate() =', A.GetCreationDate()<br>
   &nbsp;&nbsp;&nbsp; print "A.IsModified() = ", A.IsModified()<br>
   A.SetLocked(1)<br>
  <big><small><br>
  </small></big>myBuilder.AbortCommand() <i># abort all actions declared
within the created command</i><br>
 <br>
 <br>
 <big><b>void Undo () raises (<a class="el"
 href="exceptionSALOMEDS_1_1StudyBuilder_1_1LockProtection.html">LockProtection</a>)</b><b> 
<small>, </small></b></big><br>
 <big><b>void Redo ()</b></big> <big><b>raises (<a class="el"
 href="exceptionSALOMEDS_1_1StudyBuilder_1_1LockProtection.html">LockProtection</a>)</b></big><br>
 <br>
 <big><small><i><u>Create new command wich containes actions for changing 
the properties of the study, <br>
 cancel all declared actions and then redo it with the help of undo/redo
mechanism:</u></i></small></big><br>
 <br>
 A&nbsp;= myStudy.GetProperties()<br>
   A&nbsp;= aProperties._narrow(SALOMEDS.AttributeStudyProperties)<br>
    <br>
   myBuilder = myStudy.NewBuilder()<br>
    <br>
   myBuilder.NewCommand() <i> # creates a new command</i><br>
    <br>
    <i># change the properties of the study</i><br>
    if A.IsLocked() == 0 :<br>
    &nbsp;&nbsp;&nbsp; A.SetUserName("tester"); print 'A.SetUserName("tester"), 
A.GetUserName() = ', A.GetUserName()<br>
    &nbsp;&nbsp;&nbsp; A.SetCreationDate(11,11,11,11,2002); print 'A.SetCreationDate(11,11,11,11,2002), 
A.GetCreationDate() =', A.GetCreationDate()<br>
    &nbsp;&nbsp;&nbsp; print "A.IsModified() = ", A.IsModified()<br>
    A.SetLocked(1)<br>
   <big><small><br>
 </small></big>myBuilder.CommitCommand() <i># commits all actions declared 
within the created command</i><br>
 <big><small><br>
  </small></big>myBuilder.Undo() <i># cancels all actions of the command<br>
 <br>
 </i>myBuilder.Redo() <i># redoes all actions of the command</i><br>
 <i><br>
 <br>
 <br>
 </i> 
<div align="center"><small><small><u><big><big><a
 name="SALOMEDS::StudyManager_impl"></a><font color="#000000"
 face="Helvetica, Arial, sans-serif"><big><big><b>SALOMEDS::StudyManager
interface</b></big></big></font></big></big></u></small></small><br>
 </div>
 <i><br>
 <br>
 <br>
 </i><big><b><a class="el" href="interfaceSALOMEDS_1_1Study.html">Study</a> 
NewStudy ( in string <i>study_name</i> )</b></big><br>
 <i><br>
 <u>Create the study with the name "Test_Study":</u></i><br>
 <br>
 myNewStudy = myStudyManager.NewStudy("Test_Study")<br>
 <br>
 <br>
 <big><b><a class="el" href="interfaceSALOMEDS_1_1Study.html">Study</a> Open
( in </b></big><a class="el" href="namespaceSALOMEDS.html#a0">URL</a><big><b> 
<i>aStudyUrl</i> ) raises </b></big>(<a class="el"
 href="exceptionSALOME_1_1SALOME__Exception.html">SALOME::SALOME_Exception</a>)<br>
 <br>
 <i><u>Open the study saved in the HDF file:</u></i><br>
 <br>
 file = 'saved_study.hdf'<br>
 <br>
 openedStudy=myStudyManager.Open(file)<br>
 <br>
 if openedStudy == None:<br>
 &nbsp;&nbsp;&nbsp; raise&nbsp; RuntimeError, "Can't open saved study!"<br>
 <br>
 <br>
 <big><b>void Save (in&nbsp;<a class="el"
 href="interfaceSALOMEDS_1_1Study.html">Study</a> <i>aStudy</i>, in boolean
<i>theMultifile</i> )</b></big><big><b><br>
 <br>
 </b><small><u><i>Open study, import med file into it and save with the old 
path and filename:</i></u></small><b><br>
 <br>
 </b></big>file = "saved_study.hdf"<br>
 myMedFile ="medfile.med"<br>
  <br>
  openedStudy=myStudyManager.Open(file)<br>
  <br>
 myVisu.SetCurrentStudy(openedStudy)<br>
 myResult = myVisu.ImportFile(myMedFile)<br>
 <br>
 myStudyManager.Save(openedStudy, 0)<br>
 <br>
 <big><b><br>
 void SaveAs ( in <small><a class="el" href="namespaceSALOMEDS.html#a0">URL</a></small> 
<i>aUrl</i>, in&nbsp;<small> <a class="el"
 href="interfaceSALOMEDS_1_1Study.html">Study</a> </small><i>aStudy</i>,
&nbsp;<small><em></em></small></b></big><big><b>in boolean <i>theMultifile
</i>)</b><br>
 <br>
 <small><u><i>Open study from the file and resave it in several files (using 
Multifile option while saving)</i></u></small><br>
 <br>
 </big>file = "saved_study.hdf"<br>
 newfile = "resaved_study.hdf"<br>
 <br>
 openedStudy=myStudyManager.Open(file)<br>
   myStudyManager.SaveAs(newfile, openedStudy, 1)<br>
 <big><br>
 <br>
 void Close ( in&nbsp; <a class="el"
 href="interfaceSALOMEDS_1_1Study.html">Study</a> aStudy )</big><br>
 <br>
 <u><i>Close just opened study:</i></u><br>
 <br>
 file = "saved_study.hdf"<br>
 <br>
  openedStudy=myStudyManager.Open(file)<br>
    myStudyManager.Close(openedStudy)<br>
 <br>
 <br>
 <br>
 
<div align="center"><small><small><u><big><big><a
 name="SALOMEDS::SObject_impl"></a><font color="#000000"
 face="Helvetica, Arial, sans-serif"><big><big><b>SALOMEDS::SObject interface</b></big></big></font></big></big></u></small></small><br>
 </div>
 <br>
 <br>
 <br>
 <big><b><a class="el" href="namespaceSALOMEDS.html#a1">ID</a> GetID ()</b></big><br>
 <br>
 <u><i>Create new SObject and get its ID:</i></u><br>
 <br>
 mySObj = myBuilder.NewObject(myFather)<br>
 <br>
 myID = &nbsp;mySObj.GetID()<br>
 <br>
 <br>
 <big><b><a class="el" href="interfaceSALOMEDS_1_1SComponent.html">SComponent</a> 
GetFatherComponent ()</b></big><br>
 <br>
 <u><i>Get father component of the SObject:</i></u><br>
 <br>
 myFather = mySObj.GetFatherComponent();<br>
 <br>
 <br>
 <big><b>boolean FindAttribute ( out&nbsp;<a class="el"
 href="interfaceSALOMEDS_1_1GenericAttribute.html">GenericAttribute</a> <i>anAttribute</i>,
in string <i>aTypeOfAttribute </i>)</b></big><br>
 <br>
 <u><i>Find the AttributeName attribute of the field:</i></u><br>
 <br>
 aFieldSObj&nbsp; = myStudy.FindObject("Head, -")<br>
  <br>
  res = aFieldSObj.FindAttribute( anAttr, "AttributeName")<br>
  if res == 0:<br>
   &nbsp;&nbsp;&nbsp; raise&nbsp; RuntimeError, "Error:&nbsp; Attribute not 
found"<br>
 <br>
 <br>
 <big><b><a class="el" href="namespaceSALOMEDS.html#a9">ListOfAttributes</a> 
GetAllAttributes ()</b></big><br>
 <br>
 <i><u>Get list of all attributes of the SObject, find the number of attributes:</u></i><br>
 <br>
 attrs = mySObj.GetAllAttributes()<br>
 aLen = len(attrs) <i># number of attributes</i><br>
 <br>
 <br>
 <br>
 <br>
 
<div align="center"><small><small><u><big><big><a
 name="SALOMEDS::SComponent_impl"></a><font color="#000000"
 face="Helvetica, Arial, sans-serif"><big><big><b>SALOMEDS::SComponent interface</b></big></big></font></big></big></u></small></small><br>
 </div>
 <br>
 <br>
 <br>
 <big><b>string ComponentDataType ()</b></big><br>
 <br>
 <i><u><a name="ComponentIterator_ex"></a>Print names of all components wich 
the study contains:</u></i><br>
 <br>
 aCompItr = myStudy.NewComponentIterator() <br>
 <br>
 while aCompItr.More():<br>
 &nbsp;&nbsp;&nbsp; aComp = aCompItr.Value()<br>
 &nbsp;&nbsp;&nbsp; aName = aComp.ComponentDataType()<br>
 &nbsp;&nbsp;&nbsp; print "Component name = ", aName<br>
 &nbsp;&nbsp;&nbsp; aCompItr.Next()<br>
 <br>
 <br>
 <i><b>Other methods are inherited.</b></i><br>
 <br>
 <br>
 <br>
 <br>
 
<div align="center"><small><small><u><big><big><a
 name="SALOMEDS::SComponentIterator_impl"></a><font color="#000000"
 face="Helvetica, Arial, sans-serif"><big><big><b>SALOMEDS::SComponentIterator
 interface</b></big></big></font></big></big></u></small></small><br>
 </div>
 <br>
 <br>
 <br>
 <big><b>boolean More (), </b><b>void Next (), </b></big><big><b><a
 class="el" href="interfaceSALOMEDS_1_1SComponent.html">SComponent</a> Value
()</b></big><br>
 <br>
 <big><i><small>See <a href="examples_Study.html#ComponentIterator_ex">another 
example</a></small></i></big><br>
 <br>
 &nbsp;&nbsp; <br>
 <br>
 
<div align="center"><small><small><u><big><big><a
 name="SALOMEDS::ChildIterator_impl"></a><font color="#000000"
 face="Helvetica, Arial, sans-serif"><big><big><b>SALOMEDS::ChildIterator
 interface</b></big></big></font></big></big></u></small></small><br>
 </div>
 <br>
 <br>
 <br>
 <big><b>boolean More () , void Next (), <a class="el"
 href="interfaceSALOMEDS_1_1SObject.html">SObject</a> Value ()</b></big><br>
 <br>
 <u><i>Print all mesh names of imported MED file with the help of ChildIterator:</i></u><br>
 <br>
 aResult = myVisu.ImportFile("MedFile.med")<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
 myStudy = theVisu.GetCurrentStudy()<br>
 aSObj = myLocalStudy.FindObjectIOR(aResult.GetID())<br>
 <br>
 aMeshIter = myLocalStudy.NewChildIterator(aSObj);&nbsp;<i> # creating new 
child iterator</i><br>
 <br>
 while aMeshIter.More() : &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp; <i># check if one more
child level exists.     </i><br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; aMeshSObj = aMeshIter.Value() 
&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;# <i>returns the SObject corresponding 
to the current object found by the iterator.      </i>&nbsp;<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; aMeshIter.Next() <i>&nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp;# passes the iterator to the next level.     </i><br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; anAttr = aMeshSObj.FindAttribute("AttributeName")[1]<br>
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; if anAttr is None :<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
aMeshSObj = aMeshIter.Value()<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; 
&nbsp; aMeshIter.Next()<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 
anAttr = aMeshSObj.FindAttribute("AttributeName")[1]<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; anAttr = anAttr._narrow(SALOMEDS.AttributeName);<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; aMeshName = anAttr.Value()<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print "&nbsp; ", aMeshName<br>
 <br>
 <br>
 <br>
 
<div align="center"><small><small><u><big><big><a
 name="SALOMEDS::AttributeComment_impl"
 href="#SALOMEDS::AttributeComment_impl"></a><font color="#000000"
 face="Helvetica, Arial, sans-serif"><big><big><b>SALOMEDS::AttributeComment
 interface</b></big></big></font></big></big></u></small></small><br>
 </div>
 <br>
 <br>
 <big><b>string Value (), &nbsp;void SetValue ( in string <i>value </i>)</b></big><br>
 <br>
 <u><i>Find the AttributeComment attribute of the "Head" field in the study, 
print it, then change it to "My Comment" string:</i></u><br>
 <br>
 aFieldSObj&nbsp; = myStudy.FindObject("Head, -")<br>
 anAttr = aFieldSObj.FindAttribute("AttributeComment")[1]<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
anAttr = anAttr._narrow(SALOMEDS.AttributeComment);<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
aFieldComment = anAttr.Value()<br>
 <br>
 print "AttributeComment", anAttr<br>
 <br>
 anAttr.SetValue ("My Comment")<br>
 
<pre></pre>
 <br>
</body>
</html>
