<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"><HTML>
<HEAD>
<!-- hennerik CVSweb $Revision$ -->
<TITLE>Example</TITLE></HEAD>
<BODY BGCOLOR="#eeeeee">
<HR noshade><PRE>#%AttributeComment interface(creations/saving/restoring)%
#%SALOMEDS methods : FindOrCreateAttribute, SaveAs FindComponent FindAttribute &nbsp;Open%
#%Attribute methods : Value, SetValue%

# &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;create &nbsp; &nbsp; AttributeComment 
#===========================================================
A = batchmode_geompy.myBuilder.FindOrCreateAttribute(batchmode_geompy.father, &quot;AttributeComment&quot;)
if A == None :
 &nbsp; &nbsp; &nbsp; &nbsp;raise &nbsp;RuntimeError, &quot;Can't create AttributeComment attribute&quot;
A = A._narrow(SALOMEDS.AttributeComment)

if A == None :
 &nbsp; &nbsp; &nbsp; &nbsp;raise &nbsp;RuntimeError, &quot;Can't create AttributeComment attribute&quot;

A.SetValue(&quot;GEOM&quot;)


# &nbsp; &nbsp; &nbsp;save / restore study &nbsp; &nbsp; &nbsp;
#============================================================
str= os.getenv(&quot;TmpDir&quot;)
if str == None:
 &nbsp; &nbsp; &nbsp; &nbsp;str = &quot;/tmp&quot;
file = str+&quot;/test.hdf&quot;

batchmode_geompy.myStudyManager.SaveAs(file, batchmode_geompy.myStudy)
openedStudy = batchmode_geompy.myStudyManager.Open(file);

if openedStudy == None:
 &nbsp; &nbsp; &nbsp; &nbsp;raise &nbsp;RuntimeError, &quot;Can't open saved study!&quot;

father = openedStudy.FindComponent(&quot;GEOM&quot;)
if father is None:
 &nbsp; &nbsp; &nbsp; &nbsp; raise &nbsp;RuntimeError, &quot;Geom component is not found! &nbsp;Wrong study is opened.&quot; 


# &nbsp; &nbsp; &nbsp;find &nbsp; &nbsp;AttributeComment
#============================================================

res,A=father.FindAttribute(&quot;AttributeComment&quot;)
if res == 0 or A == None:
 &nbsp; &nbsp; &nbsp; &nbsp;raise &nbsp;RuntimeError, &quot;Error: &nbsp;not found AttributeComment&quot;

A = A._narrow(SALOMEDS.AttributeComment)

if A == None :
 &nbsp; &nbsp; &nbsp; &nbsp;raise &nbsp;RuntimeError, &quot;Can't create AttributeComment attribute&quot;

if A.Value() != &quot;GEOM&quot;:
 &nbsp; &nbsp; &nbsp; &nbsp;&quot;Error: wrong value of AttributeComment&quot;

</PRE>